### PR TITLE
Add gzipfiles module

### PR DESCRIPTION
**Pull request by Parashurama**
Create/Read/Append a gzipped file.
Also add new tests for gzipfiles

### CODE REVIEW

**Comment by dom96** [comment]
The same functionality is already offered by my [``untar`` package](https://github.com/dom96/untar/blob/master/src/untar/gzip.nim). Perhaps it would be better to create a PR for that adding the missing functionality (the ability to seek for example)

**Comment by Parashurama** [comment]
They are not actually the same thing.
This is a simple gzip file stream completely independent from TAR.
I am also in the process of writing a tarfiles module that would used uncompressed, gzipstream, or even bzip2stream and lzma/xz/lzstream as output.
The tarfiles module is currently almost completely done.
The other compressed methods will be slower to be published as they don't have any ready-made file implementation.

**Comment by dom96** [comment]
How are they not? Mine can be used independent of tar as well. And tarfiles is precisely what the other modules in my package offer(?)

**Comment by Parashurama** [comment]
Except yours can only untar TAR archives with USTAR format. (the most commonly used)
I'm certainly not opposed to merging my work with yours, but 'untar' would need to be renamed to something more relevant.

**Comment by dom96** [comment]
Hrm, I dunno. Maybe you should create a ``tar`` package then?

**Comment by Parashurama** [comment]
Well ideally there should only be one TAR package that does everything.
You could rename your package as needed and I add functionality as a series of PR
or
I create a new package named ```tar```/```tarfiles``` with all functionality and you mark your package as deprecated.

**Comment by dom96** [comment]
Okay, I think you should simply create your own package. I'd like to keep mine because I have some software that depends on it, maybe I'll deprecate it later.

**Comment by Parashurama** [comment]
Can we revisit this PR?
Pure gzip files (aka .gz files) can be very useful in some cases and it makes sense to put it into the zip module.

**Pull request merged**
