### PR TITLE
Fixed extractAll proc

### PR DESCRIPTION
**Pull request by karantin2020**
In linux extractAll proc was incorrect.
code

``` sh
for file in walkFiles(z):
-    if file.endsWith("/"):
-      createDir(dest / file)
-    else:
-      extractFile(z, file, dest / file)
```

didn't give any string that ended with "/". 
walkFiles returns files with full archive paths only. So it couldn't create any directory.
Current code gives error:

``` sh
Traceback (most recent call last)
ziptest.nim(20)          ziptest
ziptest.nim(15)          main
zipfiles.nim(179)        extractAll
zipfiles.nim(168)        extractFile
zipfiles.nim(160)        extractFile
streams.nim(154)         write
streams.nim(130)         writeData
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/home/allecs/Workspace/Nim-lang/src/karantin2020/nimtests/ziptest/ziptest '
```

with test app:

``` nim
import os, zip/zipfiles

proc main() =
  var filename: string
  try:
    filename = paramStr(1)
  except:
    filename = "test.xlsx"
  var z: ZipArchive
  if not z.open(filename):
    echo "Opening zip failed"
    quit(1)
  z.extractAll("td")

when not defined(testing) and isMainModule:
  main()
```

My changes fix that error

### CODE REVIEW

**Comment by Araq** [comment]
Can you add the test to a newly created tests/ subdir?

**Comment by karantin2020** [comment]
Yes. I'll do it in few hours today.

**Comment by karantin2020** [comment]
Did it

**Comment by dom96** [comment]
Should the `td` folder be included in Git? It seems the tests produce it, no? So it should be added to .gitignore.

**Comment by karantin2020** [comment]
Ok, did it

**Comment by dom96** [comment]
TIL xlsx files are zips. @Araq please review.

**Pull request merged**
